CREATE TABLE work_order (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  wo_code VARCHAR(32) NOT NULL UNIQUE,
  title VARCHAR(128),
  category VARCHAR(32),
  priority INT,
  sla_minutes INT,
  status VARCHAR(16),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
